import { AhfDevice } from 'domain/ahf-device/ahf-device.types';

const DEFAULT_DEVICE_AHF: AhfDevice = {
  info: {
    Company: '1',
    FW: 'FW',
    ID: 1,
    Status: 1,
    Type: 'type',
  },
  structure: {
    DeviceID: 1,
    FolderNames: ['folder1', 'folder2', 'folder3'],
    FolderData: {
      folder1: {
        Folders: {
          'folder1.1': {
            Folders: {
              'folder1.2': {
                Folders: {},
                Params: {
                  ParData: [
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 1,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 2,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 3,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 4,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 5,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 6,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 7,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 8,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                    {
                      AccessType: '1',
                      Description: ['description1Eng', 'description1Ger'],
                      Name: ['name1Eng', 'name1Ger'],
                      ParamEnumNumb: 1,
                      ParamEnumText: ['1'],
                      ParamID: 9,
                      ParamType: 'paramType1',
                      Unit: 'unit1',
                      Value: 'value1',
                    },
                  ],
                },
              },
            },
            Params: {
              ParData: [
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 1,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 2,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 3,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 4,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 5,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 6,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 7,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 8,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 9,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 10,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 11,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 12,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 13,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 14,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 15,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 16,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
                {
                  AccessType: '1',
                  Description: ['description1Eng', 'description1Ger'],
                  Name: ['name1Eng', 'name1Ger'],
                  ParamEnumNumb: 1,
                  ParamEnumText: ['1'],
                  ParamID: 17,
                  ParamType: 'paramType1',
                  Unit: 'unit1',
                  Value: 'value1',
                },
              ],
            },
          },
        },
        Params: {
          ParData: [
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 1,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 2,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 3,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 4,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 5,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 6,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 7,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 8,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
            {
              AccessType: '1',
              Description: ['description1Eng', 'description1Ger'],
              Name: ['name1Eng', 'name1Ger'],
              ParamEnumNumb: 1,
              ParamEnumText: ['1'],
              ParamID: 9,
              ParamType: 'paramType1',
              Unit: 'unit1',
              Value: 'value1',
            },
          ],
        },
      },
    },
  },
};

export const buildDeviceAhf = (overrides = {}): AhfDevice => ({
  ...DEFAULT_DEVICE_AHF,
  ...overrides,
});
